name: 'Hassfest Validation'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  schedule:
    # Every day at midnight
    - cron:  '0 0 * * *'

jobs:
  # https://developers.home-assistant.io/blog/2020/04/16/hassfest
  validate:
    runs-on: ubuntu-latest
    steps:
        - name: Run hassfest validation
          uses: home-assistant/actions/hassfest@master